trigger:
- master

variables:

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  sqldbsgname: 'onemediasqldb-rg'
  sqldblocation: 'northeurope'
  subscription : 'melonserviceconn'
  ziprepo: 'tmp'

stages:
- stage: Build
  displayName: onemedia-sqldb-CI
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
      
    steps:
    - task: AzureCLI@1
      displayName: 'Create Resource Group and structure'
      inputs:
        azureSubscription: $(subscription)
        scriptLocation: inlineScript
        inlineScript: 'az group create --location $(sqldblocation) --name $(sqldbsgname)'
        useGlobalConfig: true
    
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'melonserviceconn'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(sqldbsgname)'
        location: '$(sqldblocation)'
        templateLocation: 'Linked artifact'
        csmFile: 'templates/data_env_infra/arm_sql_database/sqldeploy.json'
        deploymentMode: 'Incremental'

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: |
         scripts/**
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
        

- stage: Release
  displayName: onemedia-sqldb-CD
  dependsOn: Build
  condition: succeeded('Build')
  jobs:
  - deployment: Dev
    displayName: Release
    environment: 'development'
    pool: 
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@1
            displayName: 'Download Pipeline Artifact'
            inputs:
              buildType: 'current'

          - task: AzurePowerShell@4
            displayName: 'Call logic app validation : POST'
            inputs:
              azureSubscription: $(subscription)
              scriptType: filePath
              scriptPath: $(Build.ArtifactStagingDirectory)/scripts/SQLcallLogicApp.ps1
              azurePowerShellVersion: latestVersion
              
              

